services:
  nodejs:
    build: ./merge
    image: merge
    container_name: merge
    ports:
      - "3000:3000"
    volumes:
      - data:/data
      - ./merge/uploads:/app/uploads
    env_file:
      - ./.env

volumes:
  data:
